version: "3.1"

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    command: redis-server --save 60 1 --loglevel warning --requirepass '<REDIS_PASSWORD>'
    ports:
      - 6379:6379
    expose:
      - 6379
